# Generated by Django 4.0.5 on 2022-06-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('category_alt', models.TextField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_comment', models.TextField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_review', models.TextField(blank=True, max_length=400, null=True)),
                ('product_text', models.TextField(blank=True, max_length=700, null=True)),
                ('product_sale', models.IntegerField(blank=True, null=True)),
                ('product_alt', models.TextField(blank=True, max_length=700, null=True)),
                ('product_legs', models.IntegerField(blank=True, null=True)),
                ('product_pillow', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('product_color', models.ManyToManyField(blank=True, to='app.color')),
                ('product_material', models.ManyToManyField(blank=True, to='app.material')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial_name', models.CharField(blank=True, max_length=50, null=True)),
                ('testimonial_review', models.TextField(blank=True, max_length=400, null=True)),
                ('testimonial_text', models.TextField(blank=True, max_length=700, null=True)),
                ('testimonial_alt', models.TextField(blank=True, max_length=700, null=True)),
                ('testimonial_pro', models.CharField(blank=True, max_length=150, null=True)),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
